export const FRICTION =
  "Friction is the force that opposes motion between any surfaces that are in contact. There are four types of friction: static, sliding, rolling, and fluid friction. Static friction acts on objects when they are resting on a surface. For example, if you are hiking in the woods, there is static friction between your shoes and the trail each time you put down your foot (see Figure below). Without this static friction, your feet would slip out from under you, making it difficult to walk. Sliding friction is friction that acts on objects when they are sliding over a surface. Sliding friction is weaker than static friction. That's why it's easier to slide a piece of furniture over the floor after you start it moving than it is to get it moving in the first place. Sliding friction can be useful. For example, you use sliding friction when you write with a pencil. The pencil “lead” slides easily over the paper, but there's just enough friction between the pencil and paper to leave a mark.";
export const DOUBLE_PENDULUM =
  "In physics and mathematics, in the area of dynamical systems, a double pendulum is a pendulum with another pendulum attached to its end, is a simple physical system that exhibits rich dynamic behavior with a strong sensitivity to initial conditions.[1] The motion of a double pendulum is governed by a set of coupled ordinary differential equations and is chaotic. A double pendulum released from a small initial angle behaves similarly to the single pendulum. On the other hand, releasing it from a large enough initial angle will produce chaotic behaviour which is impossible to predict. Why are double pendulums so chaotic? A double pendulum executes simple harmonic motion (two normal modes) when displacements from equilibrium are small. However, when large displacements are imposed, the non-linear system becomes dramatically chaotic in its motion and demonstrates that deterministic systems are not necessarily predictable";
export const AIR_RESISTANCE =
  "By definition, air resistance describes the forces that are in opposition to the relative motion of an object as it passes through the air. These drag forces act opposite to the oncoming flow velocity, thus slowing the object down. Unlike other resistance forces, drag depends directly on velocity, since it is the component of the net aerodynamic force acting opposite to the direction of the movement. Another way to put it would be to say that air resistance is the result of collisions of the object’s leading surface with air molecules. It can therefore be said that the two most common factors that have a direct effect upon the amount of air resistance are the speed of the object and the cross-sectional area of the object. Ergo, both increased speeds and cross-sectional areas will result in an increased amount of air resistance.";
export const NEWTONS_CRADLE =
  "The Newton's cradle is a device that demonstrates the conservation of momentum and the conservation of energy with swinging spheres. When one sphere at the end is lifted and released, it strikes the stationary spheres, transmitting a force through the stationary spheres that pushes the last sphere upward. The last sphere swings back and strikes the nearly stationary spheres, repeating the effect in the opposite direction. Despite its seemingly simple design, the Newton's cradle and its swinging, clicking balls isn't just an ordinary desk toy. It is, in fact, an elegant demonstration of some of the most fundamental laws of physics and mechanics. The toy illustrates the three main physics principles at work: conservation of energy, conservation of momentum and friction.";
export const PROJECTILE_MOTION =
  "Projectile motion is a form of motion experienced by an object or particle (a projectile) that is projected near the Earth's surface and moves along a curved path under the action of gravity only (in particular, the effects of air resistance are passive and assumed to be negligible). This curved path was shown by Galileo to be a parabola, but may also be a line in the special case when it is thrown directly upwards. The study of such motions is called ballistics, and such a trajectory is a ballistic trajectory. The only force of mathematical significance that is actively exerted on the object is gravity, which acts downward, thus imparting to the object a downward acceleration towards the Earth’s center of mass. Because of the object's inertia, no external force is needed to maintain the horizontal velocity component of the object's motion. Taking other forces into account, such as aerodynamic drag or internal propulsion (such as in a rocket), requires additional analysis. A ballistic missile is a missile only guided during the relatively brief initial powered phase of flight, and whose remaining course is governed by the laws of classical mechanics";
